account/urls.py
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_req, name="login"),
    path("logout/", views.logout_request, name="logout"),
]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    # Home page
    path("", views.home, name="post"),
    path("post/detail/<int:id>", views.post_detail, name="post-detail"),
    path("post/create/", views.create_post, name="create-post"),
    path("person/<int:id>", views.view_person, name="view-person"),
    path("follow-<int:person_id>/", views.follow, name="follow"),
    path("unfollow-<int:person_id>/", views.unfollow, name="unfollow"),
    path("like-<int:post_id>/", views.like, name="like"),
    path("unlike-<int:post_id>/", views.unlike, name="unlike"),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

social_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

blog/models.py
import datetime as dt


from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    caption = models.CharField(max_length=65)
    content = models.TextField(blank=True)
    upload_file = models.FileField(
        upload_to="videos",
        blank=True,
        validators=[FileExtensionValidator(["mp4", "jpeg", "png", "jpg"])],
    )
    create_date = models.DateTimeField(default=dt.datetime.now)
    updated_date = models.DateTimeField(default=dt.datetime.now)

    def __str__(self):
        return self.name


class FollowedPerson(models.Model):
    person = models.ForeignKey(User, related_name="person", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="user", on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=dt.datetime.now)

    class Meta:
        unique_together = (("person", "user"),)


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        result = self.post.name + " liked by " + self.user.username
        return result

account/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm


class RegisterForm(UserCreationForm):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    required_css_class = "required"

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "password",
        )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

blog/forms.py
from django import forms
from django.conf import settings
from django.forms import ModelForm
from django.template.defaultfilters import filesizeformat

from .models import Post


class CreatePostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["name", "caption", "upload_file", "content"]

    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

account/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import LoginForm, RegisterForm


# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("blog:post")
    else:
        form = RegisterForm()

    context = {
        "form": form,
    }
    return render(request, "register.html", context)


def login_req(request):
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:

                login(request, user)
                if "next" in request.POST:
                    return redirect(request.POST.get("next"))
                else:
                    return redirect("blog:post")
    else:
        form = LoginForm()

    context = {"login_form": form}
    return render(request, "login.html", context)


def logout_request(request):
    logout(request)
    return redirect("account:login")

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CreatePostForm
from .models import FollowedPerson, Like, Post

# Create your views here.


def home(request):
    user = request.user
    posts = Post.objects.filter(user_id=user.id).order_by("create_date")
    users = User.objects.exclude(id=user.id).order_by("-date_joined")
    context = {
        "posts": posts,
        "users": users,
    }
    return render(request, "post.html", context)


def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    post_detail = Post.objects.filter(id=post.id)
    user_is_liked = Like.objects.filter(
        post_id=post.id, user=request.user
    ).exists()
    liked_count = 0
    liked_count = Like.objects.filter(post_id=post.id).count()
    context = {
        "post_detail": post_detail,
        "user_is_liked": user_is_liked,
        "liked_count": liked_count,
    }
    return render(request, "details.html", context)


def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = request.user
            data.save()
            return redirect("blog:post")
    else:
        form = CreatePostForm()
    context = {"form": form}
    return render(request, "create.html", context)


def view_person(request, id):
    user = get_object_or_404(User, id=id)
    posts = Post.objects.filter(user_id=user.id)
    user_is_following = FollowedPerson.objects.filter(
        person=user, user=request.user
    ).exists()
    context = {
        "posts": posts,
        "user_is_following": user_is_following,
        "user": user,
    }
    return render(request, "view_person.html", context)


def follow(request, person_id):
    person = get_object_or_404(User, id=person_id)
    FollowedPerson.objects.create(person=person, user=request.user)
    return redirect("blog:view-person", person.id)


def unfollow(request, person_id):
    person = get_object_or_404(User, id=person_id)
    FollowedPerson.objects.filter(person=person, user=request.user).delete()
    return redirect("blog:view-person", person.id)


def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    Like.objects.create(post_id=post.id, user=request.user)
    return redirect("blog:post-detail", post.id)


def unlike(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    Like.objects.filter(post_id=post.id, user=request.user).delete()
    return redirect("blog:post-detail", post.id)

account/templates/login.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="card m-5">
                <div class="card-title text-center py-4">
                    <h1>Welcome to User</h1>
                </div>
                <div class="card-body ">
                  <form action="" method="post">
                    {% csrf_token %}
                    {{login_form.as_p}}
                    {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{request.GET.next}}">
                    {% endif %}
                    <input type="submit" class="btn p-2 btn-success" value="Login">
                  </form>
                </div>
                <div class="card-footer">
                  <a class="btn  p-2 btn-danger btn-block rounded-pill" href="{% url 'account:register' %}"> <i class="fa fa-user-circle" aria-hidden="true"></i> Register</a>
                  <small class="small-text"> If you don't have account then Register ! <i class="fa fa-smile-o" aria-hidden="true"></i>  </small>
                
            </div>
        </div>
        
    </div>
</div>

{% endblock content %}

account/templates/register.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-md-6 m-5">
            <div class="card">
                <div class="card-title text-center py-4">
                    <h1>Regiter User</h1>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="Submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<title>Title</title>
</head>
<body>

    {% include 'include/header.html' %}
    {% block content %}
    {% endblock content %}
    

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/create.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      <h1>Create Post</h1>
      <hr />
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            {{form.as_p}}

            <input type="submit" value="Submit" class="btn btn-primary" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row d-flex justify-content-center p-5">
    <div class="col-md-8">
      <div class="card post-card ">
        <div class="card-header">
          <h1 class="h1">Recent Feeds</h1>
        </div>
        {% for post in post_detail  %}
        {% if post.upload_file.url|slice:"-4:" == ".mp4" %}
          <video src="{{post.upload_file.url}}" autoplay="true" loop="true" controls=true></video>
          <p class="m-1 text-danger">{{post.caption|title}}</>
        {% else %}
          <img src="{{post.upload_file.url}}" alt="">
          <p class="m-1 text-danger">{{post.caption|title}}</>
        {% endif %}
        <div class="card-body p-2">
          <div class="card-titie">
            <h5 class="m-0">{{post.name}}</h5>
            <p class="text-justify">
              {{post.content}}
            </p>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-between">
          <p>{{post.create_date|timesince}} ago. | Post Create By:{{post.user.username}}</p>
          <p>
            <form method="POST" class="">
                  {% csrf_token %}

                  {% if user_is_liked %}

                  <button class="btn btn-danger" type="submit" formaction="{% url 'blog:unlike' post.id %}">
                      <i class="fa fa-heartbeat" aria-hidden="true"></i> Unlike
                  </button>
                  {% else %}
                  <button class="btn btn-primary" type="submit" formaction="{% url 'blog:like' post.id %}">
                      <i class="fa fa-heart" aria-hidden="true"></i>
                      Like 
                  </button>
                  
                  {% endif %}
              </form>
              <button class="btn btn-outline-primary">
                <i class="fa fa-thumbs-up" aria-hidden="true"></i> {{liked_count}}
              </button>
          </p>
      </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/include/footer.html
        {% load static %}
        <!-- Footer-->
        <footer class="footer">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Kanchan Yadav 2022</div>
                    </div>
                </div>
            </div>
        </footer>

blog/templates/include/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="nav-brand">
        <h4 class="text-dark"> <i class="fa fa-user-circle fa-warning" aria-hidden="true"></i> Welcome back {% if request.user.is_authenticated %} {{request.user.username}} {% else %} Guest {% endif %}</h4>
      </div>
      <ul class="navbar-nav ms-auto py-4 py-lg-0 d-flex align-items-center">

        <li class="nav-item"><a class="nav-link mx-3" href="{% url 'blog:post' %}">Feeds</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a class="nav-link mx-3 btn btn-outline-danger" href="{% url 'account:logout' %}">Log Out</a></li>
        <li class="nav-item"><a class="nav-link mx-3 btn btn-outline-primary" href="{% url 'blog:create-post' %}">Create Post <i class="fa fa-plus" aria-hidden="true"></i> </a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link mx-2 btn btn-primary " href="{% url 'account:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

blog/templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row d-flex justify-content-center p-5">
    <div class="col-md-8">
      <div class="card post-card  border-primary">
        <div class="card-header">
          <h1 class="h1">My Recent Feeds</h1>
        </div>
        {% for blog in posts %}
        <div class="card-body p-2">
          <div class="card-titie">
            <h5 class="m-0">{{blog.name}}</h5>
          </div>
          <div class="card-text">
            <span class="captions">{{blog.caption}}</span>
            <p><i class="fas fa-user-circle small-text"></i> Post By: {{blog.user}}</p>
            <a href="{% url 'blog:post-detail' blog.id %}"  
            target="_blank" rel="noopener noreferrer" 
            class="btn btn-outline-primary p-2">
            View 
            <i class="fa fa-eye" aria-hidden="true"></i></a>
          </div>

        </div>
        <hr>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-4">
      <div class="card post-card border-danger">
        <div class="card-header">
          <h1 class="h1">Follow Person</h1>
        </div>
        <div class="card-body">
         
          <ul class="list-group">
          {% if request.user.is_authenticated %}
          {% for user in users  %}
          <li class="list-group-item">
            <i class="fa fa-user-circle" aria-hidden="true"></i> 
              |<a href="{% url 'blog:view-person' user.id %} ">
                {{ user.first_name }} {{ user.last_name }}
              </a>

          </li>
          {% endfor %}
          {% else %}
            <h3>Login and Register and show the person list</h3>
          {% endif %}
          
          </ul>
          
        </div>
      </div>


    </div>
  </div>
</div>
{% endblock content %}

blog/templates/view_person.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row d-flex justify-content-center p-5">
        <div class="col-md-8 d-flex justify-content-between aligin-items-center">
            <div>
                <h1>{{user.username}}</h1>
            </div>
            <div>
                <form method="POST" class="">
                    {% csrf_token %}

                    {% if user_is_following %}

                    <button class="btn btn-danger" type="submit" formaction="{% url 'blog:unfollow' user.id %}">
                        <i class="fa fa-minus" aria-hidden="true"></i> Unfollow
                    </button>
                    {% else %}
                    <button class="btn btn-primary" type="submit" formaction="{% url 'blog:follow' user.id %}">
                        <i class="fa fa-plus" aria-hidden="true"></i>
                        Follow
                    </button>
                    {% endif %}
                </form>
            </div>
        </div>
        <div class="col-md-8">
            <hr>
            <h2 class="h1">Recent Feeds</h2>
            <hr>
        </div>
        {% if user_is_following %}


        {% for blog in posts %}
        <div class="col-md-8 mb-5">
            <div class="card">
                <div class="card-body p-2">
                    <div class="card-titie">
                      <h5 class="m-0">{{blog.name}}</h5>
                    </div>
                    <div class="card-text">
                      <span class="captions">{{blog.caption}}</span>
                      <p><i class="fas fa-user-circle small-text"></i> Post By: {{blog.user}}</p>
                      <a href="{% url 'blog:post-detail' blog.id %}"  
                      target="_blank" rel="noopener noreferrer" 
                      class="btn btn-outline-primary p-2">
                      View 
                      <i class="fa fa-eye" aria-hidden="true"></i></a>
                    </div>
          
                  </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-8">
            <div class="card post-card ">
                <div class="card-body">
                    <h2>
                        Follow the Person and get the latest Post...
                    </h2>
                </div>

            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}